const Strings = {
  typing: 'Typing...',
  privacy_policy: 'PRIVACY POLICY',
  privacydescription:
    'A Privacy Policy is a legal statement that specifies what the business owner does with the personal data collected from users, along with how the data is processed and for what purposes.\n\nIn 1968, Council of Europe did studies on the threat of the Internet expansion as they were concerned with the effects of technology on human rights. This lead to the development of policies that were to be developed to protect personal data.\n\nThis marks the start of what we know now as a "Privacy Policy." While the name "Privacy Policy" refers to the legal agreement, the concept of privacy and protecting user data is closely related.',
  i_understand: 'I UNDERSTAND',
  medical_products: 'MEDICAL PRODUCTS',
  bathroom_aids: 'BATHROOM AIDS',
  general_wellness: 'GENERAL WELLNESS',
  physio_ortho: 'PHYSIO & ORTHO',
  mobility_aids: 'MOBILITY AIDS',
  leisure: 'LEISURE',
  bedroom_accessories: 'BEDROOM ACCESSORIES',
  daily_living_aids: 'DAILY LIVING AIDS',
  smart_living: 'SMART LIVING',
  kitchen_gardening: 'KITCHEN & GARDENING',
  food_diet: 'FOOD & DIET',
  evergreen_rewards: 'EVERGREEN REWARDS',
  new_arrivals: 'NEW ARRIVALS',
  best_sellers: 'BEST SELLERS',
  seniority_global: 'SENIORITY GLOBAL',
  evergreen_brand: 'EVERGREEN BRAND',
  offers: 'OFFERS',
  myaccount: 'MYACCOUNT',
  help: 'HELP',
  welcome_to_senioroty: 'Welcome to Seniority',
  live_evergreen: 'Live Evergreen',
  blog: 'Blog',
  welseniority: "India's largest online shopping destination for seniors ",
  liveevergreentext:
    'Thoughtfully crafted products curated for all your daily needs',
  blogtext: 'Listen to blog as podcast',
  myprofile: 'My Profile',
  select_image: 'SELECT IMAGE',
  link:'Link your social accounts'
};
export default Strings;
